// Code generated by qtc from "footer.qtpl". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

//line transport/http/html/quicktemplate/templates/footer.qtpl:2
package templates

//line transport/http/html/quicktemplate/templates/footer.qtpl:2
import "time"

//line transport/http/html/quicktemplate/templates/footer.qtpl:4
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line transport/http/html/quicktemplate/templates/footer.qtpl:4
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line transport/http/html/quicktemplate/templates/footer.qtpl:5
type Footer struct{}

//line transport/http/html/quicktemplate/templates/footer.qtpl:8
func (h *Footer) StreamFooter(qw422016 *qt422016.Writer, current string, month time.Time) {
//line transport/http/html/quicktemplate/templates/footer.qtpl:8
	qw422016.N().S(`<footer class="footer"><div class="footer__content">`)
//line transport/http/html/quicktemplate/templates/footer.qtpl:11
	if current == "expenses" {
//line transport/http/html/quicktemplate/templates/footer.qtpl:11
		qw422016.N().S(`<a class="footer__btn btn btn--active"><img class="btn__icon" src="/static/img/expenses.svg" alt="支出"></a>`)
//line transport/http/html/quicktemplate/templates/footer.qtpl:15
	} else {
//line transport/http/html/quicktemplate/templates/footer.qtpl:15
		qw422016.N().S(`<a class="footer__btn btn" href="/expenses/`)
//line transport/http/html/quicktemplate/templates/footer.qtpl:16
		qw422016.E().S(month.Format("2006/01"))
//line transport/http/html/quicktemplate/templates/footer.qtpl:16
		qw422016.N().S(`#bottom"><img class="btn__icon" src="/static/img/expenses.svg" alt="支出"></a>`)
//line transport/http/html/quicktemplate/templates/footer.qtpl:19
	}
//line transport/http/html/quicktemplate/templates/footer.qtpl:21
	if current == "incomes" {
//line transport/http/html/quicktemplate/templates/footer.qtpl:21
		qw422016.N().S(`<a class="footer__btn btn btn--active"><img class="btn__icon" src="/static/img/income.svg" alt="収入"></a>`)
//line transport/http/html/quicktemplate/templates/footer.qtpl:25
	} else {
//line transport/http/html/quicktemplate/templates/footer.qtpl:25
		qw422016.N().S(`<a class="footer__btn btn" href="/incomes/`)
//line transport/http/html/quicktemplate/templates/footer.qtpl:26
		qw422016.E().S(month.Format("2006/01"))
//line transport/http/html/quicktemplate/templates/footer.qtpl:26
		qw422016.N().S(`#bottom"><img class="btn__icon" src="/static/img/income.svg" alt="収入"></a>`)
//line transport/http/html/quicktemplate/templates/footer.qtpl:29
	}
//line transport/http/html/quicktemplate/templates/footer.qtpl:29
	qw422016.N().S(`</div><div class="footer__cutout"></div><a class="modal__open footer__btn--main" data-modal="add" data-target="/`)
//line transport/http/html/quicktemplate/templates/footer.qtpl:33
	qw422016.E().S(current)
//line transport/http/html/quicktemplate/templates/footer.qtpl:33
	qw422016.N().S(`">+</a></footer>`)
//line transport/http/html/quicktemplate/templates/footer.qtpl:35
}

//line transport/http/html/quicktemplate/templates/footer.qtpl:35
func (h *Footer) WriteFooter(qq422016 qtio422016.Writer, current string, month time.Time) {
//line transport/http/html/quicktemplate/templates/footer.qtpl:35
	qw422016 := qt422016.AcquireWriter(qq422016)
//line transport/http/html/quicktemplate/templates/footer.qtpl:35
	h.StreamFooter(qw422016, current, month)
//line transport/http/html/quicktemplate/templates/footer.qtpl:35
	qt422016.ReleaseWriter(qw422016)
//line transport/http/html/quicktemplate/templates/footer.qtpl:35
}

//line transport/http/html/quicktemplate/templates/footer.qtpl:35
func (h *Footer) Footer(current string, month time.Time) string {
//line transport/http/html/quicktemplate/templates/footer.qtpl:35
	qb422016 := qt422016.AcquireByteBuffer()
//line transport/http/html/quicktemplate/templates/footer.qtpl:35
	h.WriteFooter(qb422016, current, month)
//line transport/http/html/quicktemplate/templates/footer.qtpl:35
	qs422016 := string(qb422016.B)
//line transport/http/html/quicktemplate/templates/footer.qtpl:35
	qt422016.ReleaseByteBuffer(qb422016)
//line transport/http/html/quicktemplate/templates/footer.qtpl:35
	return qs422016
//line transport/http/html/quicktemplate/templates/footer.qtpl:35
}
