// Code generated by qtc from "header.qtpl". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

//line transport/http/html/quicktemplate/templates/header.qtpl:2
package templates

//line transport/http/html/quicktemplate/templates/header.qtpl:2
import "time"

//line transport/http/html/quicktemplate/templates/header.qtpl:4
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line transport/http/html/quicktemplate/templates/header.qtpl:4
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line transport/http/html/quicktemplate/templates/header.qtpl:5
type Header struct{}

//line transport/http/html/quicktemplate/templates/header.qtpl:8
func (h *Header) StreamHeader(qw422016 *qt422016.Writer, current string, month time.Time) {
//line transport/http/html/quicktemplate/templates/header.qtpl:8
	qw422016.N().S(`<header class="header"><div class="header__content"><a id="nav-prev" class="header__btn header__btn--left btn" href="/`)
//line transport/http/html/quicktemplate/templates/header.qtpl:11
	qw422016.E().S(current)
//line transport/http/html/quicktemplate/templates/header.qtpl:11
	qw422016.N().S(`/`)
//line transport/http/html/quicktemplate/templates/header.qtpl:11
	qw422016.E().S(month.AddDate(0, -1, 0).Format("2006/01"))
//line transport/http/html/quicktemplate/templates/header.qtpl:11
	qw422016.N().S(`#bottom"><img class="btn__icon" src="/static/img/arrow_left.svg"></a><div class="header__heading">`)
//line transport/http/html/quicktemplate/templates/header.qtpl:14
	qw422016.E().S(current)
//line transport/http/html/quicktemplate/templates/header.qtpl:14
	qw422016.N().S(`</div><a id="nav-next" class="header__btn header__btn--right btn" href="/`)
//line transport/http/html/quicktemplate/templates/header.qtpl:15
	qw422016.E().S(current)
//line transport/http/html/quicktemplate/templates/header.qtpl:15
	qw422016.N().S(`/`)
//line transport/http/html/quicktemplate/templates/header.qtpl:15
	qw422016.E().S(month.AddDate(0, 1, 0).Format("2006/01"))
//line transport/http/html/quicktemplate/templates/header.qtpl:15
	qw422016.N().S(`#bottom"><img class="btn__icon" src="/static/img/arrow_right.svg"></a></div></header>`)
//line transport/http/html/quicktemplate/templates/header.qtpl:20
}

//line transport/http/html/quicktemplate/templates/header.qtpl:20
func (h *Header) WriteHeader(qq422016 qtio422016.Writer, current string, month time.Time) {
//line transport/http/html/quicktemplate/templates/header.qtpl:20
	qw422016 := qt422016.AcquireWriter(qq422016)
//line transport/http/html/quicktemplate/templates/header.qtpl:20
	h.StreamHeader(qw422016, current, month)
//line transport/http/html/quicktemplate/templates/header.qtpl:20
	qt422016.ReleaseWriter(qw422016)
//line transport/http/html/quicktemplate/templates/header.qtpl:20
}

//line transport/http/html/quicktemplate/templates/header.qtpl:20
func (h *Header) Header(current string, month time.Time) string {
//line transport/http/html/quicktemplate/templates/header.qtpl:20
	qb422016 := qt422016.AcquireByteBuffer()
//line transport/http/html/quicktemplate/templates/header.qtpl:20
	h.WriteHeader(qb422016, current, month)
//line transport/http/html/quicktemplate/templates/header.qtpl:20
	qs422016 := string(qb422016.B)
//line transport/http/html/quicktemplate/templates/header.qtpl:20
	qt422016.ReleaseByteBuffer(qb422016)
//line transport/http/html/quicktemplate/templates/header.qtpl:20
	return qs422016
//line transport/http/html/quicktemplate/templates/header.qtpl:20
}
