// Code generated by qtc from "html_base.qtpl". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

//line transport/http/html/quicktemplate/templates/html_base.qtpl:3
package templates

//line transport/http/html/quicktemplate/templates/html_base.qtpl:3
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line transport/http/html/quicktemplate/templates/html_base.qtpl:3
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line transport/http/html/quicktemplate/templates/html_base.qtpl:4
type Layout interface {
//line transport/http/html/quicktemplate/templates/html_base.qtpl:4
	Title() string
//line transport/http/html/quicktemplate/templates/html_base.qtpl:4
	StreamTitle(qw422016 *qt422016.Writer)
//line transport/http/html/quicktemplate/templates/html_base.qtpl:4
	WriteTitle(qq422016 qtio422016.Writer)
//line transport/http/html/quicktemplate/templates/html_base.qtpl:4
	Body() string
//line transport/http/html/quicktemplate/templates/html_base.qtpl:4
	StreamBody(qw422016 *qt422016.Writer)
//line transport/http/html/quicktemplate/templates/html_base.qtpl:4
	WriteBody(qq422016 qtio422016.Writer)
//line transport/http/html/quicktemplate/templates/html_base.qtpl:4
}

//line transport/http/html/quicktemplate/templates/html_base.qtpl:11
type Base struct {
	SubTitle string
}

//line transport/http/html/quicktemplate/templates/html_base.qtpl:15
func (b *Base) StreamTitle(qw422016 *qt422016.Writer) {
//line transport/http/html/quicktemplate/templates/html_base.qtpl:15
	qw422016.E().S(b.SubTitle)
//line transport/http/html/quicktemplate/templates/html_base.qtpl:15
}

//line transport/http/html/quicktemplate/templates/html_base.qtpl:15
func (b *Base) WriteTitle(qq422016 qtio422016.Writer) {
//line transport/http/html/quicktemplate/templates/html_base.qtpl:15
	qw422016 := qt422016.AcquireWriter(qq422016)
//line transport/http/html/quicktemplate/templates/html_base.qtpl:15
	b.StreamTitle(qw422016)
//line transport/http/html/quicktemplate/templates/html_base.qtpl:15
	qt422016.ReleaseWriter(qw422016)
//line transport/http/html/quicktemplate/templates/html_base.qtpl:15
}

//line transport/http/html/quicktemplate/templates/html_base.qtpl:15
func (b *Base) Title() string {
//line transport/http/html/quicktemplate/templates/html_base.qtpl:15
	qb422016 := qt422016.AcquireByteBuffer()
//line transport/http/html/quicktemplate/templates/html_base.qtpl:15
	b.WriteTitle(qb422016)
//line transport/http/html/quicktemplate/templates/html_base.qtpl:15
	qs422016 := string(qb422016.B)
//line transport/http/html/quicktemplate/templates/html_base.qtpl:15
	qt422016.ReleaseByteBuffer(qb422016)
//line transport/http/html/quicktemplate/templates/html_base.qtpl:15
	return qs422016
//line transport/http/html/quicktemplate/templates/html_base.qtpl:15
}

//line transport/http/html/quicktemplate/templates/html_base.qtpl:17
func StreamPage(qw422016 *qt422016.Writer, l Layout) {
//line transport/http/html/quicktemplate/templates/html_base.qtpl:17
	qw422016.N().S(`<!doctype html><html lang="ja"><head><title>`)
//line transport/http/html/quicktemplate/templates/html_base.qtpl:22
	l.StreamTitle(qw422016)
//line transport/http/html/quicktemplate/templates/html_base.qtpl:22
	qw422016.N().S(` `)
//line transport/http/html/quicktemplate/templates/html_base.qtpl:22
	qw422016.N().S(`| 家計簿</title><meta charset="UTF-8"><meta name="viewport" content="width=device-width, initial-scale=1.0"><meta name="robots" content="noindex" /><link rel="icon" type="image/x-icon" href="/common/favicon.ico"><link rel="stylesheet" href="/static/css/main.css"></head><body>`)
//line transport/http/html/quicktemplate/templates/html_base.qtpl:31
	l.StreamBody(qw422016)
//line transport/http/html/quicktemplate/templates/html_base.qtpl:31
	qw422016.N().S(`</body></html>`)
//line transport/http/html/quicktemplate/templates/html_base.qtpl:35
}

//line transport/http/html/quicktemplate/templates/html_base.qtpl:35
func WritePage(qq422016 qtio422016.Writer, l Layout) {
//line transport/http/html/quicktemplate/templates/html_base.qtpl:35
	qw422016 := qt422016.AcquireWriter(qq422016)
//line transport/http/html/quicktemplate/templates/html_base.qtpl:35
	StreamPage(qw422016, l)
//line transport/http/html/quicktemplate/templates/html_base.qtpl:35
	qt422016.ReleaseWriter(qw422016)
//line transport/http/html/quicktemplate/templates/html_base.qtpl:35
}

//line transport/http/html/quicktemplate/templates/html_base.qtpl:35
func Page(l Layout) string {
//line transport/http/html/quicktemplate/templates/html_base.qtpl:35
	qb422016 := qt422016.AcquireByteBuffer()
//line transport/http/html/quicktemplate/templates/html_base.qtpl:35
	WritePage(qb422016, l)
//line transport/http/html/quicktemplate/templates/html_base.qtpl:35
	qs422016 := string(qb422016.B)
//line transport/http/html/quicktemplate/templates/html_base.qtpl:35
	qt422016.ReleaseByteBuffer(qb422016)
//line transport/http/html/quicktemplate/templates/html_base.qtpl:35
	return qs422016
//line transport/http/html/quicktemplate/templates/html_base.qtpl:35
}
